/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

// Check if running under Bun
if (typeof process.versions.bun === "string") {
  // Static loading for Bun compile
  // Bun needs static require paths to bundle the .node files
  try {
    switch (platform) {
      case 'android':
        switch (arch) {
          case 'arm64':
            nativeBinding = require('./index.android-arm64.node')
            break
          case 'arm':
            nativeBinding = require('./index.android-arm-eabi.node')
            break
          default:
            throw new Error(`Unsupported architecture on Android ${arch}`)
        }
        break
      case 'win32':
        switch (arch) {
          case 'x64':
            nativeBinding = require('./index.win32-x64-msvc.node')
            break
          case 'ia32':
            nativeBinding = require('./index.win32-ia32-msvc.node')
            break
          case 'arm64':
            nativeBinding = require('./index.win32-arm64-msvc.node')
            break
          default:
            throw new Error(`Unsupported architecture on Windows: ${arch}`)
        }
        break
      case 'darwin':
        // Try universal first
        try {
          nativeBinding = require('./index.darwin-universal.node')
        } catch {
          // Fall back to architecture-specific
          switch (arch) {
            case 'x64':
              nativeBinding = require('./index.darwin-x64.node')
              break
            case 'arm64':
              nativeBinding = require('./index.darwin-arm64.node')
              break
            default:
              throw new Error(`Unsupported architecture on macOS: ${arch}`)
          }
        }
        break
      case 'freebsd':
        if (arch !== 'x64') {
          throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
        }
        nativeBinding = require('./index.freebsd-x64.node')
        break
      case 'linux':
        switch (arch) {
          case 'x64':
            if (isMusl()) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('./index.linux-x64-gnu.node')
            }
            break
          case 'arm64':
            if (isMusl()) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            }
            break
          case 'arm':
            nativeBinding = require('./index.linux-arm-gnueabihf.node')
            break
          default:
            throw new Error(`Unsupported architecture on Linux: ${arch}`)
        }
        break
      default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
    }
  } catch (e) {
    loadError = e
  }
} else {
  // Dynamic loading for Node.js (original behavior)
  switch (platform) {
    case 'android':
      switch (arch) {
        case 'arm64':
          localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.android-arm64.node')
            } else {
              nativeBinding = require('@bindrs/rfd-android-arm64')
            }
          } catch (e) {
            loadError = e
          }
          break
        case 'arm':
          localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.android-arm-eabi.node')
            } else {
              nativeBinding = require('@bindrs/rfd-android-arm-eabi')
            }
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Android ${arch}`)
      }
      break
    case 'win32':
      switch (arch) {
        case 'x64':
          localFileExisted = existsSync(
            join(__dirname, 'index.win32-x64-msvc.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.win32-x64-msvc.node')
            } else {
              nativeBinding = require('@bindrs/rfd-win32-x64-msvc')
            }
          } catch (e) {
            loadError = e
          }
          break
        case 'ia32':
          localFileExisted = existsSync(
            join(__dirname, 'index.win32-ia32-msvc.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.win32-ia32-msvc.node')
            } else {
              nativeBinding = require('@bindrs/rfd-win32-ia32-msvc')
            }
          } catch (e) {
            loadError = e
          }
          break
        case 'arm64':
          localFileExisted = existsSync(
            join(__dirname, 'index.win32-arm64-msvc.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.win32-arm64-msvc.node')
            } else {
              nativeBinding = require('@bindrs/rfd-win32-arm64-msvc')
            }
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Windows: ${arch}`)
      }
      break
    case 'darwin':
      localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
      try {
        if (localFileExisted) {
          nativeBinding = require('./index.darwin-universal.node')
        } else {
          nativeBinding = require('@bindrs/rfd-darwin-universal')
        }
        break
      } catch {}
      switch (arch) {
        case 'x64':
          localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.darwin-x64.node')
            } else {
              nativeBinding = require('@bindrs/rfd-darwin-x64')
            }
          } catch (e) {
            loadError = e
          }
          break
        case 'arm64':
          localFileExisted = existsSync(
            join(__dirname, 'index.darwin-arm64.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.darwin-arm64.node')
            } else {
              nativeBinding = require('@bindrs/rfd-darwin-arm64')
            }
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on macOS: ${arch}`)
      }
      break
    case 'freebsd':
      if (arch !== 'x64') {
        throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
      }
      localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
      try {
        if (localFileExisted) {
          nativeBinding = require('./index.freebsd-x64.node')
        } else {
          nativeBinding = require('@bindrs/rfd-freebsd-x64')
        }
      } catch (e) {
        loadError = e
      }
      break
    case 'linux':
      switch (arch) {
        case 'x64':
          if (isMusl()) {
            localFileExisted = existsSync(
              join(__dirname, 'index.linux-x64-musl.node')
            )
            try {
              if (localFileExisted) {
                nativeBinding = require('./index.linux-x64-musl.node')
              } else {
                nativeBinding = require('@bindrs/rfd-linux-x64-musl')
              }
            } catch (e) {
              loadError = e
            }
          } else {
            localFileExisted = existsSync(
              join(__dirname, 'index.linux-x64-gnu.node')
            )
            try {
              if (localFileExisted) {
                nativeBinding = require('./index.linux-x64-gnu.node')
              } else {
                nativeBinding = require('@bindrs/rfd-linux-x64-gnu')
              }
            } catch (e) {
              loadError = e
            }
          }
          break
        case 'arm64':
          if (isMusl()) {
            localFileExisted = existsSync(
              join(__dirname, 'index.linux-arm64-musl.node')
            )
            try {
              if (localFileExisted) {
                nativeBinding = require('./index.linux-arm64-musl.node')
              } else {
                nativeBinding = require('@bindrs/rfd-linux-arm64-musl')
              }
            } catch (e) {
              loadError = e
            }
          } else {
            localFileExisted = existsSync(
              join(__dirname, 'index.linux-arm64-gnu.node')
            )
            try {
              if (localFileExisted) {
                nativeBinding = require('./index.linux-arm64-gnu.node')
              } else {
                nativeBinding = require('@bindrs/rfd-linux-arm64-gnu')
              }
            } catch (e) {
              loadError = e
            }
          }
          break
        case 'arm':
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@bindrs/rfd-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
          break
        default:
          throw new Error(`Unsupported architecture on Linux: ${arch}`)
      }
      break
    default:
      throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { AsyncFileDialog, AsyncMessageDialog, FileDialog, FileHandle, MessageButtons, MessageDialog, MessageLevel } = nativeBinding

module.exports.AsyncFileDialog = AsyncFileDialog
module.exports.AsyncMessageDialog = AsyncMessageDialog
module.exports.FileDialog = FileDialog
module.exports.FileHandle = FileHandle
module.exports.MessageButtons = MessageButtons
module.exports.MessageDialog = MessageDialog
module.exports.MessageLevel = MessageLevel